SELECT * FROM customer_behavior.customer;

-- what is the total revenue generated by male vs female customers?-- 
select gender , SUM(purchase_amount) as revenue
from customer
group by gender;

-- which customers used a discount but still spent more than the average purchase amount-- 
select customer_id
from customer
where purchase_amount>( select AVG(purchase_amount) from customer) and discount_applied='Yes';

-- which are the top 5 products with the highest average review rating
select distinct item_purchased
from customer
group  by item_purchased
order by AVG(review_rating) desc
limit 5;

-- compare the average purchase amounts between standard and express shipping 
select shipping_type,AVG(purchase_amount)
from customer
where shipping_type in('Standard','Express')
group by shipping_type;

-- do subcribed customers spend more ? compare average spend and total revenue between subcribers and non subcribers 
select subscription_status,COUNT(customer_id), ROUND(AVG(purchase_amount),2) , SUM(purchase_amount)
from customer
group by subscription_status;

-- which 5 products have the highest percentage of purchase with discounts applied?
select distinct item_purchased ,
ROUND(SUM(CASE WHEN discount_applied='Yes' THEN 1 ELSE 0 END)/COUNT(*) * 100 , 2) as discount_rate
from customer
group by item_purchased
order by discount_rate desc
limit 5;

-- segment customers into new, returning , and loyal based on their total
-- number of previous purchases , and show the count of each segment 
with customer_type as (
select customer_id  , previous_purchases,
CASE
    WHEN previous_purchases = 1 THEN 'New'
    WHEN previous_purchases BETWEEN 2 AND 10 THEN 'Returning'
    ELSE 'Loyal'
    END 
    as customer_segment
from customer
)

select customer_segment , count(*) as "Number of Customers"
from customer_type
group by customer_segment;

-- what are the top 3 most purchased products within each category 
with item_counts as (
select category ,
       item_purchased,
       COUNT(customer_id) as total_orders ,
       ROW_NUMBER() over(partition by category order by count(customer_id) desc) as item_rank
       from customer
       group by category, item_purchased
       )
       
       select  item_rank , category , item_purchased , total_orders
       from item_counts
       where item_rank<=3;

-- are customers who are repeat buyers (more than 5 previous purchases) also likely to subscribe?
select subscription_status,
count(customer_id) as repeat_buyers
from customer
where previous_purchases>5
group by subscription_status;

-- what is the revenue by age group
select age_group,
SUM(purchase_amount) as total_revenue
from customer
group by age_group
order by total_revenue desc;



